routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::group(['middleware' => 'auth'], function () {

    Route::get('getproducts', 'ProductController@getProducts');
    Route::post('import-file', 'ProductController@importCsvExcel')->name('import-file');
    Route::resource('products', 'ProductController');
    Route::get('/home', 'HomeController@index')->name('home');

});

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Product extends Model
{
    use SoftDeletes;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'sku',
        'price',
        'install_fee',
        'quantity',
        'description',
        'image',
    ];
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Product;
use Redirect;
use Session;
use Storage;
use URL;
use DataTables;
use Excel;
use Response;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('products.products');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('products.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //validation
        $request->validate([
            'name' => 'required|alpha_num|max:255',
            'sku' => 'required|alpha_num',
            'price' => 'required|regex:/(^\d{1,10}(\.\d{1,2})?$)/',
            'install_fee' => 'required|numeric',
            'quantity' => 'required|numeric',
            'description' => 'required',
            'image' => 'required|mimes:jpeg,jpg,png',
        ]);

        if ($request->hasFile('image')) {

            $originalName = $request->file('image')->getClientOriginalName();

            $imageName = time(). '-' . $originalName;

            $file = $request->file('image');

            Storage::put(
                'images/products/'.$imageName,
                file_get_contents($file->getRealPath())
            );

            $image_path = 'products/'.$imageName;
        }

        $product = new Product();

        $product->name = $request->name;
        $product->sku = $request->sku;
        $product->price = $request->price;
        $product->install_fee = $request->install_fee;
        $product->quantity = $request->quantity;
        $product->description = $request->description;
        $product->image = $image_path;

        $product->save();

        $request->session()->flash('message', 'Product added successfully!');

        return Redirect::to('products');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $product
     * @return \Illuminate\Http\Response
     */
    public function show(Product $product)
    {
        return view('products.product')->with('product', $product);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $product
     * @return \Illuminate\Http\Response
     */
    public function edit(Request $request, Product $product)
    {
        return view('products.edit')->with('product', $product);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $product
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Product $product)
    {
        //validation
        $request->validate([
            'name' => 'required|alpha_num|max:255',
            'sku' => 'required|alpha_num',
            'price' => 'required|regex:/(^\d{1,10}(\.\d{1,2})?$)/',
            'install_fee' => 'required|numeric',
            'quantity' => 'required|numeric',
            'description' => 'required',
            'image' => 'mimes:jpeg,jpg,png',
        ]);

        $product->name = $request->name;
        $product->sku  = $request->sku;
        $product->price  = $request->price;
        $product->install_fee  = $request->install_fee;
        $product->quantity  = $request->quantity;
        $product->description  = $request->description;

        if ($request->hasFile('image')) {

            $originalName = $request->file('image')->getClientOriginalName();

            $imageName = time(). '-' . $originalName;

            $file = $request->file('image');

            Storage::put(
                'images/products/'.$imageName,
                file_get_contents($file->getRealPath())
            );

            $image_path = 'products/'.$imageName;

            Storage::delete('images/'. $product->image);

            $product->image = $image_path;
        }

        $product->save();

        $request->session()->flash('message', 'Product updated successfully!');

        return Redirect::to('products');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $product
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, Product $product)
    {
        $product->delete();

        $request->session()->flash('message', 'Product deleted successfully!');

        return Response::json(['success' => true]);
    }

    /**
     * Generate jquery datatable
     *
     */
    public function getProducts() {
        $products = Product::select(['id', 'name', 'sku', 'price', 'install_fee', 'quantity' ,'created_at', 'updated_at']);

        return Datatables::of($products)
            ->addColumn('action', function ($product) {
                $btns= '<div class="action_btns">';
                $btns .= '<a href="/products/'.$product->id.'" class="btn btn-sm btn-info">View</a>';
                $btns .= '<a href="/products/'.$product->id.'/edit" class="btn btn-sm btn-warning">Edit</a>';

                $btns .= '<button href="/products/'.$product->id.'" onclick="confirmDelete(this)" class="btn btn-sm btn-danger" product_id='. $product->id .'">Delete</button>';
                $btns .= '</div>';
                return $btns;
            })
            ->make(true);
    }

    /**
     * Import excel or csv file
     *
     */
    public function importCsvExcel(Request $request) {
        try {
            \Log::info('Importing file...');
            if ($request->hasFile('excelFile')) {
                $no = 0;
                Excel::load($request->file('excelFile')->getRealPath(), function ($reader) use($no, $request) {
                    foreach ($reader->toArray() as $key => $row) {
                        \Log::debug('data', [
                            'data' => $row
                        ]);
                        if (! empty($row['name']) && !empty($row['sku'])) {

                            $product = new Product();
                            $product->sku = $row['sku'];
                            $product->name = $row['name'];
                            $product->price = !empty($row['price']) ? $row['price'] : NULL;
                            $product->install_fee = !empty($row['install_fee']) ? $row['install_fee'] : NULL;
                            $product->quantity = !empty($row['quantity']) ? $row['quantity'] : NULL;
                            $product->description = !empty($row['description']) ? $row['description'] : NULL;
                            $product->save();
                            $no++;

                            \Log::debug('Product added.', [
                                'product_id' => $product->id,
                            ]);
                        }
                    }

                    if($no > 0) {
                        $request->session()->flash('message', 'File imported successfully');
                    } else {
                        $request->session()->flash('message', 'Sorry, File not imported! Pleaser provide valid data.');
                    }
                });

                return Redirect::to('products');
            } else {
                $request->session()->flash('message', 'File not found!');
                return Redirect::to('products');
            }
        } catch (\Exception $e) {
            $request->session()->flash('message', $e->getMessage());
            return Redirect::to('products');
        }
    }
}

resources/views/products/create.blade.php
@extends('layouts.app')
@section('content')
  <div class="container">
    <section>
      <h3 class="text-center">Add new product</h3>
    </section>
    <div class="row">
      <div class="col-lg-12">
        @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif

        <form name="productForm" id="productForm" method="post" enctype="multipart/form-data" action="{{ url('products')}}" autocomplete="off">
          {{ csrf_field() }}
          <div class="form-group">
            <label for="name">Name:</label>
            <input type="text" class="form-control" id="name" placeholder="Enter product name" name="name" value="{{ old('name') }}">
          </div>

          <div class="form-group">
            <label for="sku">Sku:</label>
            <input type="text" class="form-control" id="sku" placeholder="Enter product sku" name="sku" value="{{ old('sku') }}">
          </div>

          <div class="form-group">
            <label for="price">Price:</label>
            <input type="number" class="form-control" id="price" placeholder="Enter product price" name="price" value="{{ old('price') }}">
          </div>

          <div class="form-group">
            <label for="install_fee">Install fee:</label>
            <input type="number" class="form-control" id="install_fee" placeholder="Enter install fee" name="install_fee" value="{{ old('install_fee') }}">
          </div>

          <div class="form-group">
            <label for="quantity">Quantity:</label>
            <input type="number" class="form-control" id="quantity" placeholder="Enter enter quantity" name="quantity" value="{{ old('quantity') }}">
          </div>

          <div class="form-group">
            <label for="description">Description:</label>
            <textarea name="description" id="description" class="form-control">{{ old('description') }}</textarea>
          </div>

          <div class="form-group">
            <label for="image">Image:</label>
            <input type="file" class="form-control" id="image" name="image" accept="image/*" required="required">
          </div>

          <div class="buttons text-center">
            <button type="button" name="saveProduct" id="saveProduct" class="btn btn-success">Save</button>
            <a href="{!! URL::previous() !!}" class="btn btn-secondary">
                Cancel
            </a>
          </div>
        </form>
      </div>
    </div>
  </div>
@endsection

@push('scripts')
  <script type="text/javascript" src="{{ asset('plugins/validation/validate.min.js') }}"></script>
  <script type="text/javascript" src="{{ asset('plugins/validation/additional-methods.min.js') }}"></script>
  <script type="text/javascript" src="{{ asset('js/product.js') }}"></script>
@endpush

resources/views/products/edit.blade.php
@extends('layouts.app')
@section('content')
  <div class="container">
    <section>
      <h3 class="text-center">Edit product</h3>
    </section>
    <div class="row">
      <div class="col-lg-12">
        @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif

        <form name="productForm" id="productForm" method="post" enctype="multipart/form-data" action="{{ route('products.update', $product->id) }}" autocomplete="off">
          {{ method_field('PUT') }}
          {{ csrf_field() }}
          <div class="form-group">
            <label for="name">Name:</label>
            <input type="text" class="form-control" id="name" placeholder="Enter product name" name="name" value="{{ old('name') ? old('name') : $product->name }}">
          </div>

          <div class="form-group">
            <label for="sku">Sku:</label>
            <input type="text" class="form-control" id="sku" placeholder="Enter product sku" name="sku" value="{{ old('sku') ? old('sku') : $product->sku }}">
          </div>

          <div class="form-group">
            <label for="price">Price:</label>
            <input type="number" class="form-control" id="price" placeholder="Enter product price" name="price" value="{{ old('price') ? old('price') : $product->price }}">
          </div>

          <div class="form-group">
            <label for="install_fee">Install fee:</label>
            <input type="number" class="form-control" id="install_fee" placeholder="Enter install fee" name="install_fee" value="{{ old('install_fee') ? old('install_fee') : $product->install_fee }}">
          </div>

          <div class="form-group">
            <label for="quantity">Quantity:</label>
            <input type="number" class="form-control" id="quantity" placeholder="Enter enter quantity" name="quantity" value="{{ old('quantity') ? old('quantity') : $product->quantity }}">
          </div>

          <div class="form-group">
            <label for="description">Description:</label>
            <textarea name="description" id="description" class="form-control">{{ old('description') ? old('description') : $product->description }}</textarea>
          </div>

          <div class="form-group">
            <label for="image">Image:</label>
            <input type="file" class="form-control" id="image" name="image" accept="image/*">
            <img src="/storage/images/{{ $product->image}}" class="rounded" alt="Cinque Terre" width="200" height="200">
          </div>

          <div class="buttons text-center">
            <button type="button" name="saveProduct" id="saveProduct" class="btn btn-success">Save</button>
            <a href="{!! URL::previous() !!}" class="btn btn-secondary">
                Cancel
            </a>
          </div>
        </form>
      </div>
    </div>
  </div>
@endsection

@push('scripts')
  <script type="text/javascript" src="{{ asset('plugins/validation/validate.min.js') }}"></script>
  <script type="text/javascript" src="{{ asset('plugins/validation/additional-methods.min.js') }}"></script>
  <script type="text/javascript" src="{{ asset('js/product.js') }}"></script>
@endpush

resources/views/products/product.blade.php
@extends('layouts.app')
@section('content')
  <div class="container">
    <section>
      <h3 class="text-center">{{ $product->name }}</h3>
    </section>
    <br>
    <div class="row">
      <div class="col-lg-12">
        <div class="text-center">
          <img src="/storage/images/{{ $product->image}}" class="rounded" alt="Cinque Terre" width="200" height="200" accept="image/*">
        </div>
        <br>
        <p>
          <strong>SKU: </strong> {{$product->sku}}
        </p>
        <p>
          <strong>Price: </strong> {{$product->price}}
        </p>
        <p>
          <strong>Installation fee: </strong> {{$product->installation_fee}}
        </p>
        <p>
          <strong>Qty: </strong> {{$product->quantity}}
        </p>
        <p>
          <strong>Description: </strong> {{$product->description}}
        </p>
        <p>
          <strong>Created date: </strong> {{$product->created_at}}
        </p>
        <p>
          <strong>Updated date: </strong> {{$product->updated_at}}
        </p>

        <br>
        <a href="{!! URL::previous() !!}" class="btn btn-secondary">
                Back
            </a>
      </div>
    </div>
  </div>
@endsection

@push('scripts')
  <script type="text/javascript" src="{{ asset('plugins/validation/validate.min.js') }}"></script>
  <script type="text/javascript" src="{{ asset('plugins/validation/additional-methods.min.js') }}"></script>
  <script type="text/javascript" src="{{ asset('js/product.js') }}"></script>
@endpush

resources/views/products/products.blade.php
@extends('layouts.app')
@section('content')
  @push('additional-css')
    <link rel="stylesheet" href="{{ asset('plugins/datatables/DataTables-1.10.18/css/dataTables.bootstrap4.min.css') }}">
    <link rel="stylesheet" href="{{ asset('plugins/datatables/Buttons-1.5.4/css/buttons.bootstrap4.min.css') }}">
  @endpush
  <div class="container">
    <section style="margin-bottom: 20px;">
      <h3>Products</h3>
    </section>
    @if (session()->has('message'))
      <div class="alert alert-info">
          {{ session('message') }}
      </div>
    @endif
    <div class="row">
      <div class="col-sm-6">
        <form name="uploadExcel" method="POST" enctype="multipart/form-data" action="{{ route('import-file') }}">
          {{ csrf_field() }}
          <div class="form-group">
            <label id="excelFile">Import Csv/Excel file</label>
            <input type="file" name="excelFile" id="excelFile" class="form-control" accept=".csv, application/vnd.openxmlformats-officedocument.spreadsheetml.sheet, application/vnd.ms-excel" required>
            <button type="submit" id="uploadExcel" name="uploadExcel" class="btn btn-primary">Import</button>
          </div>
        </form>
      </div>
      <div class="col-sm-6">
        <a href="{{ url('products/create') }}" class="btn btn-success" style="float: right;">Add new</a>
      </div>

    </div>
    <br>
    <div class="row">
      <div class="col-lg-12">
          <table class="table" id="products-table">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Sku</th>
                    <th>Price</th>
                    <th>Fee</th>
                    <th>Qty</th>
                    <th>Last Updated</th>
                    <th>Action</th>
                </tr>
            </thead>
          </table>

      </div>


    </div>
  </div>
@endsection

@push('scripts')
  <script type="text/javascript" src="{{ asset('plugins/datatables/JSZip-2.5.0/jszip.min.js') }}"></script>
  <script type="text/javascript" src="{{ asset('plugins/datatables/pdfmake-0.1.36/pdfmake.min.js') }}"></script>
  <script type="text/javascript" src="{{ asset('plugins/datatables/pdfmake-0.1.36/vfs_fonts.js') }}"></script>
  <script type="text/javascript" src="{{ asset('plugins/datatables/DataTables-1.10.18/js/jquery.dataTables.min.js') }}"></script>
  <script type="text/javascript" src="{{ asset('plugins/datatables/DataTables-1.10.18/js/dataTables.bootstrap4.min.js') }}"></script>
  <script type="text/javascript" src="{{ asset('plugins/datatables/Buttons-1.5.4/js/dataTables.buttons.min.js') }}"></script>
  <script type="text/javascript" src="{{ asset('plugins/datatables/Buttons-1.5.4/js/buttons.bootstrap4.min.js') }}"></script>
  <script type="text/javascript" src="{{ asset('plugins/datatables/Buttons-1.5.4/js/buttons.flash.min.js') }}"></script>
  <script type="text/javascript" src="{{ asset('plugins/datatables/Buttons-1.5.4/js/buttons.html5.min.js') }}"></script>
  <script type="text/javascript" src="{{ asset('js/product.js') }}"></script>

  <script type="text/javascript">

    $(document).ready(function(){
      var table = $('#products-table').DataTable({
        processing: true,
        serverSide: true,
        ajax: "{{ url('getproducts') }}",
        columns: [
            {data: 'name', name: 'name'},
            {data: 'sku', name: 'sku'},
            {data: 'price', name: 'price'},
            {data: 'install_fee', name: 'install_fee'},
            {data: 'quantity', name: 'quantity'},
            {data: 'updated_at', name: 'updated_at'},
            {data: 'action', name: 'action', orderable: false, searchable: false}
        ],
        dom:"Bfrtip",
        buttons: [{
          extend: 'excel',
            text: 'Save as Excel',
            exportOptions: {
                header: false,
                columns: [ 0, 1, 2, 3, 4 ]
            },
        },
        {
          extend: 'csv',
            text: 'Save as CSV',
            exportOptions: {
                header: false,
                columns: [ 0, 1, 2, 3, 4 ]
            },
        }
        ]
      });
    });
  </script>
@endpush